[openapi_paths]
summary = "Fetch List of Animals"
operationId = "getListAnimals"
tags = ["animals"]

[openapi_paths.responses.200]
description = "An object that contains a single animal"

[openapi_paths.responses.200.content.'application/json'.schema]
'$ref' = "#/components/schemas/AnimalCollection"

[openapi_paths.responses.200.content.'application/xml'.schema]
'$ref' = "#/components/schemas/AnimalCollection"

[openapi_paths.responses.405.content.'application/json'.schema]
'$ref' = "#/components/schemas/HttpStatus"

[openapi_paths.responses.405.content.'application/xml'.schema]
'$ref' = "#/components/schemas/HttpStatus"