[openapi_paths]
summary = "Delete an animal"
operationId = "deleteAnimal"
tags = ["animals"]

[openapi_paths.requestBody.content.'application/json'.schema]
'$ref' = "#/components/schemas/DeleteAnimal"

[openapi_paths.requestBody.content.'application/xml'.schema]
'$ref' = "#/components/schemas/DeleteAnimal"

[openapi_paths.responses.200]
description = "An object that contains the message"

[openapi_paths.responses.200.content.'application/json'.schema]
'$ref' = "#/components/schemas/Message"

[openapi_paths.responses.200.content.'application/xml'.schema]
'$ref' = "#/components/schemas/Message"

[openapi_paths.responses.400.content.'application/json'.schema]
'$ref' = "#/components/schemas/HttpStatus"

[openapi_paths.responses.400.content.'application/xml'.schema]
'$ref' = "#/components/schemas/HttpStatus"

[openapi_paths.responses.404.content.'application/json'.schema]
'$ref' = "#/components/schemas/HttpStatus"

[openapi_paths.responses.404.content.'application/xml'.schema]
'$ref' = "#/components/schemas/HttpStatus"

[openapi_paths.responses.405.content.'application/json'.schema]
'$ref' = "#/components/schemas/HttpStatus"

[openapi_paths.responses.405.content.'application/xml'.schema]
'$ref' = "#/components/schemas/HttpStatus"